apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJWR0ZyWVhOWk9UUTZaMmh3WDNRd2VITjZjRGQyYjJGalkwWnVRVFp4T1hsWlZEUkRRa1pyYzNKSGJEUkRWMnBSYkE9PSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
